version: '3'

services:
  gateway-service:
    build:
      context: .
      target: development
    ports:
      - 9000:9000
      - 7000:7000
    env_file: .env
    volumes:
      - .:/home/node
    command: /bin/sh -c "npm i && npm run start:dev"
    networks:
      - bng

networks:
  bng:
    external: true
