version: '3'

services:
  gateway-service:
    image: adxl/bng-gateway:latest
    ports:
      - 80:9000
    environment:
      STAGE: production
    networks:
      - bng
    deploy:
      replicas: 3

networks:
  bng:
    external: true
