version: '3'

services:
  gateway-service:
    image: adxl/bng-gateway:latest
    ports:
      - 8080:9000
      - 7000:7000
    environment:
      STAGE: production
      INTERNAL_BASIC: '@INTERNAL_BASIC@'
    networks:
      - bng
    deploy:
      replicas: 1

networks:
  bng:
    external: true
