name: Gateway CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Tests
        run: npm run test

      - name: Build project
        run: npm run build

  publish:
    needs: build
    runs-on: ubuntu-20.04
    
    if: github.ref_name == 'master'
  
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.HUB_USERNAME }}
          password: ${{ secrets.HUB_PASSWORD }}

      - name: Build
        run: docker compose -f docker-compose.prod.yaml build

      - name: Push
        run: docker compose -f docker-compose.prod.yaml push

